### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by sebastianhakansson** [axakon/tree_app_frontend_web#3]
As a user, some means of navigating between pages is needed. This could for example be in the header or a footer, depending on which is easiest.

All users should be able to navigate between Home (`/`), My Tree (`/my-tree`) and Leaves (`/leaves`). Gardeners should also be able to navigate to My Plants (`/my-plants`).

Furthermore some pages require a back button, like this:

- `/leaves/:leafId` requires a button that redirects to `/leaves`
- `/my-plants/plantId` requires a button that redirects to `/my-plants`
- `/review/:plantId/:leafId` requires a button that redirects to `/my-plants/:plantId`

**Comment by Dnimander** [comment]
In review
